### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by Xterbione** [modded-ubuntu/modded-ubuntu#151] opened 2024-05-21 13:28 UTC
After following the setup procedure and connecting over vnc, I still hear no audio. Pavucontrol can't start cause it doesn't exist when trying to open volume mixer.. im on a s23 ultra not rooted stock firmware

**Comment by BDhackers009** [comment] 2024-05-23 19:21
It's Samsung phone bug I guess because I also have this problem on the other hand the audio works fine on realme,redmi and other devices.

You can install pavucontrol to get GUI for pulseaudio I mean to control Volume install 

$ ` sudo apt install pavucontrol -y `

**Comment by BDhackers009** [comment] 2024-06-07 13:11
Hey! The audio bug has been fixed. Please reinstall modded-ubuntu or just add 

``` pacmd load-module module-aaudio-sink ```

this line in the $HOME/.sound file. It will fix the sound issue.

**Comment by syedalauddinbuk** [comment] 2024-06-16 19:00
> Hey! The audio bug has been fixed. Please reinstall modded-ubuntu or just add 
> 
> ``` pacmd load-module module-aaudio-sink ```
> 
> this line in the $HOME/.sound file. It will fix the sound issue.

I installed  it few days ago. it doesn't work for me. given that, should i create a file name ".sound" file  in home/username directory ?

**Comment by syedalauddinbuk** [comment] 2024-06-16 19:41
it seems to solved the problem onces, you have place the command in the sound file. later, installing pavucontrol etc. but after i tired connecting my bluetooth earphone .  it doesn't work.

**Comment by BDhackers009** [comment] 2024-06-16 23:49
> it seems to solved the problem onces, you have place the command in the sound file. later, installing pavucontrol etc. but after i tired connecting my bluetooth earphone . it doesn't work.

Its for the speaker sound. After installing modded-ubuntu GUI you have to exit from termux and restart modded-ubuntu.

**Comment by syedalauddinbuk** [comment] 2024-06-17 03:00
> > it seems to solved the problem onces, you have place the command in the sound file. later, installing pavucontrol etc. but after i tired connecting my bluetooth earphone . it doesn't work.
> 
> Its for the speaker sound. After installing modded-ubuntu GUI you have to exit from termux and restart modded-ubuntu.

Okay. I actually did that. Well it's okay now. Anyways IS der any way I can connect Bluetooth earphones?

**Comment by BDhackers009** [comment] 2024-06-17 03:16
> > > it seems to solved the problem onces, you have place the command in the sound file. later, installing pavucontrol etc. but after i tired connecting my bluetooth earphone . it doesn't work.
> > 
> > 
> > Its for the speaker sound. After installing modded-ubuntu GUI you have to exit from termux and restart modded-ubuntu.
> 
> Okay. I actually did that. Well it's okay now. Anyways IS der any way I can connect Bluetooth earphones?

Connect Bluetooth earphones to your phone not modded-ubuntu. It should work.

**Comment by syedalauddinbuk** [comment] 2024-06-17 03:42
> > > > it seems to solved the problem onces, you have place the command in the sound file. later, installing pavucontrol etc. but after i tired connecting my bluetooth earphone . it doesn't work.
> > > 
> > > 
> > > Its for the speaker sound. After installing modded-ubuntu GUI you have to exit from termux and restart modded-ubuntu.
> > 
> > Okay. I actually did that. Well it's okay now. Anyways IS der any way I can connect Bluetooth earphones?
> 
> Connect Bluetooth earphones to your phone not modded-ubuntu. It should work.

Actually, I did that. it doesn't work. but i will give another try and will let you know.

**Comment by syedalauddinbuk** [comment] 2024-06-17 03:44
> > > > > it seems to solved the problem onces, you have place the command in the sound file. later, installing pavucontrol etc. but after i tired connecting my bluetooth earphone . it doesn't work.
> > > > 
> > > > 
> > > > Its for the speaker sound. After installing modded-ubuntu GUI you have to exit from termux and restart modded-ubuntu.
> > > 
> > > Okay. I actually did that. Well it's okay now. Anyways IS der any way I can connect Bluetooth earphones?
> > 
> > Connect Bluetooth earphones to your phone not modded-ubuntu. It should work.
> 
> Actually, I did that. it doesn't work. but i will give another try and will let you know.

it works.. 🫠🫠😀😀

**Comment by syedalauddinbuk** [comment] 2024-06-17 03:53
> > > > > > it seems to solved the problem onces, you have place the command in the sound file. later, installing pavucontrol etc. but after i tired connecting my bluetooth earphone . it doesn't work.
> > > > > 
> > > > > 
> > > > > Its for the speaker sound. After installing modded-ubuntu GUI you have to exit from termux and restart modded-ubuntu.
> > > > 
> > > > Okay. I actually did that. Well it's okay now. Anyways IS der any way I can connect Bluetooth earphones?
> > > 
> > > Connect Bluetooth earphones to your phone not modded-ubuntu. It should work.
> > 
> > Actually, I did that. it doesn't work. but i will give another try and will let you know.
> 
> it works.. 🫠🫠😀😀

i tested using youtube on firefox, but i tired playing another video, it keeps buffering, its not a net problem i can confirm, leading to no youtube playing.

**Comment by BDhackers009** [comment] 2024-06-17 03:56
> > > > > > > it seems to solved the problem onces, you have place the command in the sound file. later, installing pavucontrol etc. but after i tired connecting my bluetooth earphone . it doesn't work.
> > > > > > 
> > > > > > 
> > > > > > Its for the speaker sound. After installing modded-ubuntu GUI you have to exit from termux and restart modded-ubuntu.
> > > > > 
> > > > > 
> > > > > Okay. I actually did that. Well it's okay now. Anyways IS der any way I can connect Bluetooth earphones?
> > > > 
> > > > 
> > > > Connect Bluetooth earphones to your phone not modded-ubuntu. It should work.
> > > 
> > > 
> > > Actually, I did that. it doesn't work. but i will give another try and will let you know.
> > 
> > 
> > it works.. 🫠🫠😀😀
> 
> i tested using youtube on firefox, but i tired playing another video, it keeps buffering, its not a net problem i can confirm, leading to no youtube playing.

Its because proot is slow. If you want to get more performance you should use termux-x11. Search about it. Btw who watches videos on prooted environment. You have your phones app.

**Comment by syedalauddinbuk** [comment] 2024-06-17 03:56
> > > > > > > it seems to solved the problem onces, you have place the command in the sound file. later, installing pavucontrol etc. but after i tired connecting my bluetooth earphone . it doesn't work.
> > > > > > 
> > > > > > 
> > > > > > Its for the speaker sound. After installing modded-ubuntu GUI you have to exit from termux and restart modded-ubuntu.
> > > > > 
> > > > > Okay. I actually did that. Well it's okay now. Anyways IS der any way I can connect Bluetooth earphones?
> > > > 
> > > > Connect Bluetooth earphones to your phone not modded-ubuntu. It should work.
> > > 
> > > Actually, I did that. it doesn't work. but i will give another try and will let you know.
> > 
> > it works.. 🫠🫠😀😀
> 
> i tested using youtube on firefox, but i tired playing another video, it keeps buffering, its not a net problem i can confirm, leading to no youtube playing.

youtube is playing, but no audio this time.

**Comment by syedalauddinbuk** [comment] 2024-06-17 04:00
> > > > > > > > it seems to solved the problem onces, you have place the command in the sound file. later, installing pavucontrol etc. but after i tired connecting my bluetooth earphone . it doesn't work.
> > > > > > > 
> > > > > > > 
> > > > > > > Its for the speaker sound. After installing modded-ubuntu GUI you have to exit from termux and restart modded-ubuntu.
> > > > > > 
> > > > > > 
> > > > > > Okay. I actually did that. Well it's okay now. Anyways IS der any way I can connect Bluetooth earphones?
> > > > > 
> > > > > 
> > > > > Connect Bluetooth earphones to your phone not modded-ubuntu. It should work.
> > > > 
> > > > 
> > > > Actually, I did that. it doesn't work. but i will give another try and will let you know.
> > > 
> > > 
> > > it works.. 🫠🫠😀😀
> > 
> > i tested using youtube on firefox, but i tired playing another video, it keeps buffering, its not a net problem i can confirm, leading to no youtube playing.
> 
> Its because proot is slow. If you want to get more performance you should use termux-x11. Search about it. Btw who watches videos on prooted environment. You have your phones app.

haha , i knw . but i am setting up a specific env for my workspace. thats y.

**Comment by syedalauddinbuk** [comment] 2024-06-17 04:01
> > > > > > > > it seems to solved the problem onces, you have place the command in the sound file. later, installing pavucontrol etc. but after i tired connecting my bluetooth earphone . it doesn't work.
> > > > > > > 
> > > > > > > 
> > > > > > > Its for the speaker sound. After installing modded-ubuntu GUI you have to exit from termux and restart modded-ubuntu.
> > > > > > 
> > > > > > 
> > > > > > Okay. I actually did that. Well it's okay now. Anyways IS der any way I can connect Bluetooth earphones?
> > > > > 
> > > > > 
> > > > > Connect Bluetooth earphones to your phone not modded-ubuntu. It should work.
> > > > 
> > > > 
> > > > Actually, I did that. it doesn't work. but i will give another try and will let you know.
> > > 
> > > 
> > > it works.. 🫠🫠😀😀
> > 
> > i tested using youtube on firefox, but i tired playing another video, it keeps buffering, its not a net problem i can confirm, leading to no youtube playing.
> 
> Its because proot is slow. If you want to get more performance you should use termux-x11. Search about it. Btw who watches videos on prooted environment. You have your phones app.

i will look into it.

**Comment by BDhackers009** [comment] 2024-07-11 18:12
Closing this issue.

**Closed by BDhackers009** 2024-07-11 18:12 UTC
